language: node_js
node_js:
  - lts/*
script:
  - >
    yarn lerna exec "
    yarn test --coverage &&
    if [ -d coverage ]; then
      cat ./coverage/lcov.info | yarn coveralls && rm -rf ./coverage;
    fi"
