language: node_js
node_js:
  - lts/*
script:
  - yarn lerna run test:ci
  - >
    yarn lerna exec "
    if [ -d coverage ]; then
      cat ./coverage/lcov.info | yarn coveralls && rm -rf ./coverage;
    fi
    "
